### ISSUE TITLE
Download Error 

### ISSUE THREAD

**Issue by Aurentiaco35** [jusirkka/qopencpn#5]
I fixed that problem but this time the applitaction does not show anything it keep says 
kv.s52.parser.symbol: SY: unknown symbol "NEWOBJ01"
kv.s52.parser.symbol: SY: unknown symbol "FLTHAZ02"
kv.s52.parser.symbol: SY: unknown symbol "FLTHAZ02"
kv.s52.parser.symbol: SY: unknown symbol "FLTHAZ02"

kv.mgr: Unknown chartset "None"
kv.mgr: Unknown chartset "None"
kv.mgr: Unknown chartset "None"
kv.mgr: Unknown chartset "None"
kv.mgr: Unknown chartset "None"
kv.mgr: Unknown chartset "None"
kv.mgr: Unknown chartset "None"

![Application](https://github.com/jusirkka/qutenav/assets/140486360/27415bf8-1402-4f00-a67a-f300e09e0c64)

**Comment by jusirkka** [comment]
Have you added any chart folders? click  menu button -> Chart folders. Then select the folder where you have your charts. After charts have been processed, select the type of the charts: menu button -> Chartsets.

You can also dl shoreline data from https://www.ngdc.noaa.gov/mgg/shorelines/gshhs.html and install them e.g. to .local/share/gshhg/GSHHS_shp/. This provides shoreline shapes for regions where there are no map coverage .

**Comment by Aurentiaco35** [comment]
Thank you for your help. It starts working a little bit I keep trying to work with it properly. Thank you again.
